#!/usr/bin/env python3
from __future__ import annotations

import argparse
import gzip
import shutil
import subprocess
import tempfile
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a 10x-style ATAC peak MEX and per-barcode metrics table from "
            "Chromap fragments and a narrowPeak/BED peak file."
        )
    )
    parser.add_argument("--fragments", required=True, help="Chromap fragments TSV(.gz)")
    parser.add_argument("--peaks", required=True, help="narrowPeak/BED peak file")
    parser.add_argument("--out-dir", required=True, help="Output MEX directory")
    parser.add_argument(
        "--metrics-tsv",
        required=True,
        help="Output per-barcode ATAC metrics TSV",
    )
    parser.add_argument(
        "--bedtools",
        default="bedtools",
        help="bedtools executable (default: bedtools)",
    )
    parser.add_argument(
        "--max-barcodes",
        type=int,
        default=0,
        help="Optional cap on barcode count for smoke tests; 0 means no cap",
    )
    return parser.parse_args()


def open_text(path: Path, mode: str = "rt"):
    if "r" in mode:
        with open(path, "rb") as probe:
            is_gzip = probe.read(2) == b"\x1f\x8b"
    else:
        is_gzip = path.suffix == ".gz"
    if is_gzip:
        return gzip.open(path, mode)
    return open(path, mode, encoding="utf-8")


def read_peaks(path: Path) -> list[tuple[str, int, int, str]]:
    peaks: list[tuple[str, int, int, str]] = []
    with open_text(path) as handle:
        for raw in handle:
            if not raw.strip() or raw.startswith("#"):
                continue
            fields = raw.rstrip("\n").split("\t")
            if len(fields) < 3:
                continue
            chrom = fields[0]
            start = int(fields[1])
            end = int(fields[2])
            peak_id = f"{chrom}:{start}-{end}"
            peaks.append((chrom, start, end, peak_id))
    if not peaks:
        raise ValueError(f"No peaks found in {path}")
    return peaks


def write_peak_bed(peaks: list[tuple[str, int, int, str]], path: Path) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        for idx, (chrom, start, end, peak_id) in enumerate(peaks):
            handle.write(f"{chrom}\t{start}\t{end}\t{idx}\t{peak_id}\n")


def parse_fragment_fields(fields: list[str]) -> tuple[str, int]:
    if len(fields) < 4:
        raise ValueError("Fragment row has fewer than four columns")
    barcode = fields[3]
    count = int(fields[4]) if len(fields) >= 5 and fields[4] else 1
    return barcode, count


def collect_total_fragments(path: Path) -> dict[str, int]:
    totals: dict[str, int] = defaultdict(int)
    with open_text(path) as handle:
        for raw in handle:
            if not raw.strip() or raw.startswith("#"):
                continue
            fields = raw.rstrip("\n").split("\t")
            barcode, count = parse_fragment_fields(fields)
            totals[barcode] += count
    return totals


def run_bedtools(args: argparse.Namespace, peak_bed: Path, unique: bool = False):
    cmd = [
        args.bedtools,
        "intersect",
        "-a",
        str(Path(args.fragments).resolve()),
        "-b",
        str(peak_bed),
    ]
    if unique:
        cmd.append("-u")
    else:
        cmd.extend(["-wa", "-wb"])
    return subprocess.Popen(cmd, stdout=subprocess.PIPE, text=True)


def write_mex(
    out_dir: Path,
    peaks: list[tuple[str, int, int, str]],
    barcodes: list[str],
    entries: dict[tuple[int, int], int],
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    with gzip.open(out_dir / "features.tsv.gz", "wt") as handle:
        for chrom, start, end, peak_id in peaks:
            handle.write(f"{peak_id}\t{peak_id}\tPeaks\t{chrom}\t{start}\t{end}\n")
    with gzip.open(out_dir / "barcodes.tsv.gz", "wt") as handle:
        for barcode in barcodes:
            handle.write(f"{barcode}\n")
    with gzip.open(out_dir / "matrix.mtx.gz", "wt") as handle:
        handle.write("%%MatrixMarket matrix coordinate integer general\n")
        handle.write("% generated by scripts/build_atac_peak_matrix_from_fragments.py\n")
        handle.write(f"{len(peaks)} {len(barcodes)} {len(entries)}\n")
        for (peak_idx, barcode_idx), count in sorted(entries.items()):
            handle.write(f"{peak_idx + 1} {barcode_idx + 1} {count}\n")


def write_metrics(
    path: Path,
    barcodes: list[str],
    total_fragments: dict[str, int],
    peak_fragments: dict[str, int],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "barcode\tatac_fragments\tatac_peak_region_fragments\t"
            "atac_peak_region_cutsites\tatac_peak_fraction\n"
        )
        for barcode in barcodes:
            total = total_fragments.get(barcode, 0)
            peak = peak_fragments.get(barcode, 0)
            fraction = (peak / total) if total else 0.0
            handle.write(f"{barcode}\t{total}\t{peak}\t{peak * 2}\t{fraction:.8g}\n")


def main() -> None:
    args = parse_args()
    fragments = Path(args.fragments).resolve()
    peaks_path = Path(args.peaks).resolve()
    out_dir = Path(args.out_dir).resolve()
    metrics_tsv = Path(args.metrics_tsv).resolve()
    if shutil.which(args.bedtools) is None:
        raise SystemExit(f"Missing bedtools executable: {args.bedtools}")

    peaks = read_peaks(peaks_path)
    total_fragments = collect_total_fragments(fragments)
    if args.max_barcodes > 0 and len(total_fragments) > args.max_barcodes:
        keep = set(sorted(total_fragments, key=total_fragments.get, reverse=True)[: args.max_barcodes])
        total_fragments = {barcode: total_fragments[barcode] for barcode in keep}
    else:
        keep = set(total_fragments)

    entries: dict[tuple[int, int], int] = defaultdict(int)
    peak_fragments: dict[str, int] = defaultdict(int)
    barcode_to_idx: dict[str, int] = {}

    with tempfile.TemporaryDirectory(prefix="atac_peak_matrix_") as tmp:
        peak_bed = Path(tmp) / "peaks.bed"
        write_peak_bed(peaks, peak_bed)

        proc = run_bedtools(args, peak_bed, unique=True)
        assert proc.stdout is not None
        for raw in proc.stdout:
            fields = raw.rstrip("\n").split("\t")
            barcode, count = parse_fragment_fields(fields)
            if barcode in keep:
                peak_fragments[barcode] += count
        rc = proc.wait()
        if rc != 0:
            raise SystemExit(f"bedtools intersect -u failed with exit status {rc}")

        proc = run_bedtools(args, peak_bed, unique=False)
        assert proc.stdout is not None
        for raw in proc.stdout:
            fields = raw.rstrip("\n").split("\t")
            if len(fields) < 10:
                continue
            barcode, count = parse_fragment_fields(fields)
            if barcode not in keep:
                continue
            peak_idx = int(fields[-2])
            barcode_idx = barcode_to_idx.setdefault(barcode, len(barcode_to_idx))
            entries[(peak_idx, barcode_idx)] += count
        rc = proc.wait()
        if rc != 0:
            raise SystemExit(f"bedtools intersect -wa -wb failed with exit status {rc}")

    barcodes = [None] * len(barcode_to_idx)
    for barcode, idx in barcode_to_idx.items():
        barcodes[idx] = barcode
    barcodes = [barcode for barcode in barcodes if barcode is not None]
    if not barcodes:
        raise SystemExit("No peak-overlapping barcodes were found")

    write_mex(out_dir, peaks, barcodes, entries)
    write_metrics(metrics_tsv, barcodes, total_fragments, peak_fragments)
    print(f"Wrote {out_dir}")
    print(f"Wrote {metrics_tsv}")
    print(f"peaks={len(peaks)}")
    print(f"barcodes={len(barcodes)}")
    print(f"matrix_nnz={len(entries)}")


if __name__ == "__main__":
    main()
